export interface Transaction {
  id: string;
  date: string;
  description: string;
  reference: string;
  amount: number;
  currency: string;
  type: "bank" | "system";
  status: "matched" | "unmatched" | "pending" | "exception";
  matchConfidence?: number;
  category?: string;
  partner?: string;
}

export interface DashboardStats {
  totalTransactions: number;
  autoMatched: number;
  exceptions: number;
  matchRate: number;
  accounts: AccountStatus[];
}

export interface AccountStatus {
  id: string;
  name: string;
  balance: number;
  status: "reconciled" | "pending" | "critical";
  lastReconciled: string;
}

export const dashboardStats: DashboardStats = {
  totalTransactions: 3124,
  autoMatched: 2985,
  exceptions: 139,
  matchRate: 95.5,
  accounts: [
    {
      id: "1",
      name: "SGD Settlement Account",
      balance: 12450000,
      status: "reconciled",
      lastReconciled: "2024-10-30 09:35 AM",
    },
    {
      id: "2",
      name: "USD Multi-Currency Pool",
      balance: 8850000,
      status: "reconciled",
      lastReconciled: "2024-10-30 09:32 AM",
    },
    {
      id: "3",
      name: "FX Treasury Reserve",
      balance: 25200000,
      status: "pending",
      lastReconciled: "2024-10-29 04:15 PM",
    },
  ],
};

export const bankTransactions: Transaction[] = [
  {
    id: "B001",
    date: "2024-10-30",
    description: "FX SETTLEMENT - FINTECH PARTNER A",
    reference: "FX-2024-1045",
    amount: 150000,
    currency: "SGD",
    type: "bank",
    status: "exception",
    category: "FX Settlement",
    partner: "Fintech Partner A",
  },
  {
    id: "B002",
    date: "2024-10-30",
    description: "CARD SCHEME SETTLEMENT - VISA",
    reference: "VISA-2024-8842",
    amount: 45000,
    currency: "USD",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "Card Settlement",
    partner: "VISA International",
  },
  {
    id: "B003",
    date: "2024-10-30",
    description: "PLATFORM LICENSING FEE",
    reference: "LIC-Q4-1050",
    amount: 85000,
    currency: "USD",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "Platform Revenue",
    partner: "Corporate Client B",
  },
  {
    id: "B004",
    date: "2024-10-29",
    description: "CROSS-BORDER PAYMENT FEE",
    reference: "XB-FEE-10292024",
    amount: -150,
    currency: "SGD",
    type: "bank",
    status: "unmatched",
    category: "Transaction Fees",
  },
  {
    id: "B005",
    date: "2024-10-29",
    description: "TREASURY MANAGEMENT - EUR POOL",
    reference: "TRES-EUR-10252024",
    amount: 125000,
    currency: "EUR",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "Treasury",
    partner: "Bank Partner C",
  },
  {
    id: "B006",
    date: "2024-10-30",
    description: "FX SETTLEMENT USD/SGD - PARTNER B",
    reference: "FX-USD-SGD-3087",
    amount: 225000,
    currency: "SGD",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "FX Settlement",
    partner: "Fintech Partner B",
  },
  {
    id: "B007",
    date: "2024-10-30",
    description: "MASTERCARD SETTLEMENT BATCH",
    reference: "MC-BATCH-10301",
    amount: 62500,
    currency: "USD",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "Card Settlement",
    partner: "Mastercard International",
  },
  {
    id: "B008",
    date: "2024-10-29",
    description: "API TRANSACTION REVENUE - OCT",
    reference: "API-REV-OCT-2024",
    amount: 18500,
    currency: "USD",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "API Revenue",
    partner: "Corporate Client A",
  },
  {
    id: "B009",
    date: "2024-10-29",
    description: "PARTNER COMMISSION PAYOUT",
    reference: "COMM-PAY-2847",
    amount: -12000,
    currency: "SGD",
    type: "bank",
    status: "matched",
    matchConfidence: 98,
    category: "Commission",
    partner: "Fintech Partner C",
  },
  {
    id: "B010",
    date: "2024-10-28",
    description: "SWIFT WIRE TRANSFER FEE",
    reference: "SWIFT-FEE-2810",
    amount: -45,
    currency: "USD",
    type: "bank",
    status: "unmatched",
    category: "Bank Fees",
  },
  {
    id: "B011",
    date: "2024-10-30",
    description: "FX SETTLEMENT GBP/SGD",
    reference: "FX-GBP-1092",
    amount: 95000,
    currency: "SGD",
    type: "bank",
    status: "exception",
    category: "FX Settlement",
    partner: "DBS Bank",
  },
  {
    id: "B012",
    date: "2024-10-28",
    description: "UNIONPAY SETTLEMENT",
    reference: "UPI-SETTLE-2810",
    amount: 33000,
    currency: "USD",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "Card Settlement",
    partner: "UnionPay International",
  },
  {
    id: "B013",
    date: "2024-10-27",
    description: "IMPLEMENTATION SERVICE FEE",
    reference: "IMPL-FEE-Q4-09",
    amount: 75000,
    currency: "USD",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "Service Revenue",
    partner: "Corporate Client D",
  },
  {
    id: "B014",
    date: "2024-10-27",
    description: "FX SETTLEMENT EUR/USD - STRIPE",
    reference: "FX-EUR-USD-8821",
    amount: 180000,
    currency: "USD",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "FX Settlement",
    partner: "Stripe Asia",
  },
  {
    id: "B015",
    date: "2024-10-26",
    description: "INTERCHANGE REVENUE - VISA",
    reference: "INTCHG-VISA-2610",
    amount: 5200,
    currency: "USD",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "Interchange",
    partner: "VISA International",
  },
  {
    id: "B016",
    date: "2024-10-26",
    description: "MONTHLY ACCOUNT MAINTENANCE",
    reference: "MAINT-OCT-2024",
    amount: -250,
    currency: "SGD",
    type: "bank",
    status: "unmatched",
    category: "Bank Fees",
  },
  {
    id: "B017",
    date: "2024-10-30",
    description: "TREASURY JPY POOL SETTLEMENT",
    reference: "TRES-JPY-3001",
    amount: 8500000,
    currency: "JPY",
    type: "bank",
    status: "unmatched",
    category: "Treasury",
    partner: "OCBC Bank",
  },
  {
    id: "B018",
    date: "2024-10-25",
    description: "PLATFORM LICENSE - ENTERPRISE TIER",
    reference: "LIC-ENT-2510",
    amount: 120000,
    currency: "USD",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "Platform Revenue",
    partner: "Corporate Client E",
  },
  {
    id: "B019",
    date: "2024-10-25",
    description: "FX SETTLEMENT USD/EUR - ADYEN",
    reference: "FX-USD-EUR-7712",
    amount: 95000,
    currency: "EUR",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "FX Settlement",
    partner: "Adyen Singapore",
  },
  {
    id: "B020",
    date: "2024-10-28",
    description: "PARTNER COMMISSION - PARTNER D",
    reference: "COMM-PAY-2808",
    amount: -8500,
    currency: "USD",
    type: "bank",
    status: "matched",
    matchConfidence: 95,
    category: "Commission",
    partner: "Fintech Partner D",
  },
  {
    id: "B021",
    date: "2024-10-27",
    description: "CROSS-BORDER WIRE - INCOMING",
    reference: "CB-WIRE-IN-2710",
    amount: 250000,
    currency: "SGD",
    type: "bank",
    status: "unmatched",
    category: "Wire Transfer",
  },
  {
    id: "B022",
    date: "2024-10-26",
    description: "CARD SETTLEMENT - MASTERCARD",
    reference: "MC-SETTLE-2610",
    amount: 48000,
    currency: "USD",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "Card Settlement",
    partner: "Mastercard International",
  },
  {
    id: "B023",
    date: "2024-10-29",
    description: "API USAGE FEE - PREMIUM TIER",
    reference: "API-PREM-2910",
    amount: 28000,
    currency: "USD",
    type: "bank",
    status: "exception",
    category: "API Revenue",
    partner: "Corporate Client C",
  },
  {
    id: "B024",
    date: "2024-10-28",
    description: "FX SETTLEMENT GBP/USD - STANDARD CHARTERED",
    reference: "FX-GBP-USD-2845",
    amount: 165000,
    currency: "USD",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "FX Settlement",
    partner: "Standard Chartered",
  },
  {
    id: "B025",
    date: "2024-10-27",
    description: "INTERCHANGE REVENUE - MASTERCARD",
    reference: "INTCHG-MC-2710",
    amount: 3800,
    currency: "USD",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "Interchange",
    partner: "Mastercard International",
  },
];

export const systemTransactions: Transaction[] = [
  {
    id: "S001",
    date: "2024-10-30",
    description: "FX Settlement Expected - Partner A",
    reference: "FX-2024-1045",
    amount: 149850,
    currency: "SGD",
    type: "system",
    status: "exception",
    category: "FX Settlement",
    partner: "Fintech Partner A",
  },
  {
    id: "S002",
    date: "2024-10-30",
    description: "Card Scheme Settlement Booking",
    reference: "VISA-2024-8842",
    amount: 45000,
    currency: "USD",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "Card Settlement",
    partner: "VISA International",
  },
  {
    id: "S003",
    date: "2024-10-30",
    description: "Platform License Revenue Q4",
    reference: "LIC-Q4-1050",
    amount: 85000,
    currency: "USD",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "Platform Revenue",
    partner: "Corporate Client B",
  },
  {
    id: "S004",
    date: "2024-10-29",
    description: "Treasury EUR Pool Management",
    reference: "TRES-EUR-10252024",
    amount: 125000,
    currency: "EUR",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "Treasury",
    partner: "Bank Partner C",
  },
  {
    id: "S005",
    date: "2024-10-30",
    description: "FX Settlement USD/SGD Booking",
    reference: "FX-USD-SGD-3087",
    amount: 225000,
    currency: "SGD",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "FX Settlement",
    partner: "Fintech Partner B",
  },
  {
    id: "S006",
    date: "2024-10-30",
    description: "Mastercard Batch Settlement",
    reference: "MC-BATCH-10301",
    amount: 62500,
    currency: "USD",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "Card Settlement",
    partner: "Mastercard International",
  },
  {
    id: "S007",
    date: "2024-10-29",
    description: "API Transaction Revenue October",
    reference: "API-REV-OCT-2024",
    amount: 18500,
    currency: "USD",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "API Revenue",
    partner: "Corporate Client A",
  },
  {
    id: "S008",
    date: "2024-10-29",
    description: "Partner Commission Payment",
    reference: "COMM-PAY-2847",
    amount: -11975,
    currency: "SGD",
    type: "system",
    status: "matched",
    matchConfidence: 98,
    category: "Commission",
    partner: "Fintech Partner C",
  },
  {
    id: "S009",
    date: "2024-10-30",
    description: "FX Settlement GBP/SGD Expected",
    reference: "FX-GBP-1092",
    amount: 94925,
    currency: "SGD",
    type: "system",
    status: "exception",
    category: "FX Settlement",
    partner: "DBS Bank",
  },
  {
    id: "S010",
    date: "2024-10-28",
    description: "UnionPay Settlement Booking",
    reference: "UPI-SETTLE-2810",
    amount: 33000,
    currency: "USD",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "Card Settlement",
    partner: "UnionPay International",
  },
  {
    id: "S011",
    date: "2024-10-27",
    description: "Implementation Service Booking",
    reference: "IMPL-FEE-Q4-09",
    amount: 75000,
    currency: "USD",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "Service Revenue",
    partner: "Corporate Client D",
  },
  {
    id: "S012",
    date: "2024-10-27",
    description: "FX Settlement EUR/USD Stripe",
    reference: "FX-EUR-USD-8821",
    amount: 180000,
    currency: "USD",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "FX Settlement",
    partner: "Stripe Asia",
  },
  {
    id: "S013",
    date: "2024-10-26",
    description: "Interchange Revenue VISA",
    reference: "INTCHG-VISA-2610",
    amount: 5200,
    currency: "USD",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "Interchange",
    partner: "VISA International",
  },
  {
    id: "S014",
    date: "2024-10-30",
    description: "Treasury JPY Pool Expected Settlement",
    reference: "TRES-JPY-3001",
    amount: 8500000,
    currency: "JPY",
    type: "system",
    status: "pending",
    category: "Treasury",
    partner: "OCBC Bank",
  },
  {
    id: "S015",
    date: "2024-10-25",
    description: "Enterprise Platform License",
    reference: "LIC-ENT-2510",
    amount: 120000,
    currency: "USD",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "Platform Revenue",
    partner: "Corporate Client E",
  },
  {
    id: "S016",
    date: "2024-10-25",
    description: "FX Settlement USD/EUR Adyen",
    reference: "FX-USD-EUR-7712",
    amount: 95000,
    currency: "EUR",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "FX Settlement",
    partner: "Adyen Singapore",
  },
  {
    id: "S017",
    date: "2024-10-28",
    description: "Partner Commission Partner D",
    reference: "COMM-PAY-2808",
    amount: -8465,
    currency: "USD",
    type: "system",
    status: "matched",
    matchConfidence: 95,
    category: "Commission",
    partner: "Fintech Partner D",
  },
  {
    id: "S018",
    date: "2024-10-26",
    description: "Mastercard Settlement",
    reference: "MC-SETTLE-2610",
    amount: 48000,
    currency: "USD",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "Card Settlement",
    partner: "Mastercard International",
  },
  {
    id: "S019",
    date: "2024-10-29",
    description: "API Usage Premium Tier",
    reference: "API-PREM-2910",
    amount: 27950,
    currency: "USD",
    type: "system",
    status: "exception",
    category: "API Revenue",
    partner: "Corporate Client C",
  },
  {
    id: "S020",
    date: "2024-10-28",
    description: "FX Settlement GBP/USD Standard Chartered",
    reference: "FX-GBP-USD-2845",
    amount: 165000,
    currency: "USD",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "FX Settlement",
    partner: "Standard Chartered",
  },
  {
    id: "S021",
    date: "2024-10-27",
    description: "Interchange Revenue Mastercard",
    reference: "INTCHG-MC-2710",
    amount: 3800,
    currency: "USD",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "Interchange",
    partner: "Mastercard International",
  },
  {
    id: "S022",
    date: "2024-10-29",
    description: "Partner Settlement Expected - Partner E",
    reference: "PART-SETTLE-E-2910",
    amount: 55000,
    currency: "SGD",
    type: "system",
    status: "pending",
    category: "Partner Settlement",
    partner: "Fintech Partner E",
  },
  {
    id: "S023",
    date: "2024-10-26",
    description: "Cross-Currency Swap Fee Expected",
    reference: "SWAP-FEE-2610",
    amount: -320,
    currency: "USD",
    type: "system",
    status: "unmatched",
    category: "FX Fees",
  },
];

export interface MatchAdjustment {
  type: "fx_spread" | "timing" | "fee" | "other";
  amount: number;
  currency: string;
  description: string;
}

export interface MatchRecord {
  id: string;
  bankTransactionId: string;
  systemTransactionId: string;
  matchedAt: string;
  matchedBy: string;
  matchType: "auto" | "manual";
  matchConfidence: number;
  adjustments?: MatchAdjustment[];
  notes?: string;
}

export interface Exception {
  id: string;
  type: "timing" | "duplicate" | "amount_mismatch" | "unmatched";
  severity: "low" | "medium" | "high";
  bankTransaction?: Transaction;
  systemTransaction?: Transaction;
  suggestedAction?: string;
  description: string;
}

export const matchRecords: MatchRecord[] = [
  {
    id: "M001",
    bankTransactionId: "B002",
    systemTransactionId: "S002",
    matchedAt: "2024-10-30T09:35:00Z",
    matchedBy: "sarah.chen@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "Exact match on reference and amount",
  },
  {
    id: "M002",
    bankTransactionId: "B003",
    systemTransactionId: "S003",
    matchedAt: "2024-10-30T09:32:00Z",
    matchedBy: "sarah.chen@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "Platform license revenue Q4",
  },
  {
    id: "M003",
    bankTransactionId: "B005",
    systemTransactionId: "S004",
    matchedAt: "2024-10-29T16:18:00Z",
    matchedBy: "michael.wong@matchmaker.io",
    matchType: "manual",
    matchConfidence: 95,
    notes: "Treasury EUR pool management - manual verification required",
  },
  {
    id: "M004",
    bankTransactionId: "B006",
    systemTransactionId: "S005",
    matchedAt: "2024-10-30T09:40:00Z",
    matchedBy: "sarah.chen@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "USD/SGD FX settlement - exact match",
  },
  {
    id: "M005",
    bankTransactionId: "B007",
    systemTransactionId: "S006",
    matchedAt: "2024-10-30T09:38:00Z",
    matchedBy: "sarah.chen@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "Mastercard batch settlement",
  },
  {
    id: "M006",
    bankTransactionId: "B008",
    systemTransactionId: "S007",
    matchedAt: "2024-10-29T14:22:00Z",
    matchedBy: "sarah.chen@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "API revenue October",
  },
  {
    id: "M007",
    bankTransactionId: "B009",
    systemTransactionId: "S008",
    matchedAt: "2024-10-29T15:10:00Z",
    matchedBy: "jessica.tan@matchmaker.io",
    matchType: "manual",
    matchConfidence: 98,
    adjustments: [
      {
        type: "fee",
        amount: -25,
        currency: "SGD",
        description: "Bank processing fee adjustment",
      },
    ],
    notes: "Partner commission with bank fee adjustment",
  },
  {
    id: "M008",
    bankTransactionId: "B012",
    systemTransactionId: "S010",
    matchedAt: "2024-10-28T11:05:00Z",
    matchedBy: "sarah.chen@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "UnionPay settlement",
  },
  {
    id: "M009",
    bankTransactionId: "B013",
    systemTransactionId: "S011",
    matchedAt: "2024-10-27T16:30:00Z",
    matchedBy: "michael.wong@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "Implementation service fee",
  },
  {
    id: "M010",
    bankTransactionId: "B014",
    systemTransactionId: "S012",
    matchedAt: "2024-10-27T14:15:00Z",
    matchedBy: "sarah.chen@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "EUR/USD FX settlement via Stripe",
  },
  {
    id: "M011",
    bankTransactionId: "B015",
    systemTransactionId: "S013",
    matchedAt: "2024-10-26T10:20:00Z",
    matchedBy: "sarah.chen@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "VISA interchange revenue",
  },
  {
    id: "M012",
    bankTransactionId: "B018",
    systemTransactionId: "S015",
    matchedAt: "2024-10-25T13:45:00Z",
    matchedBy: "sarah.chen@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "Enterprise tier platform license",
  },
  {
    id: "M013",
    bankTransactionId: "B019",
    systemTransactionId: "S016",
    matchedAt: "2024-10-25T15:00:00Z",
    matchedBy: "michael.wong@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "USD/EUR FX via Adyen",
  },
  {
    id: "M014",
    bankTransactionId: "B020",
    systemTransactionId: "S017",
    matchedAt: "2024-10-28T09:50:00Z",
    matchedBy: "jessica.tan@matchmaker.io",
    matchType: "manual",
    matchConfidence: 95,
    adjustments: [
      {
        type: "fee",
        amount: -35,
        currency: "USD",
        description: "Wire transfer fee deduction",
      },
    ],
    notes: "Partner D commission with wire fee adjustment",
  },
  {
    id: "M015",
    bankTransactionId: "B022",
    systemTransactionId: "S018",
    matchedAt: "2024-10-26T11:30:00Z",
    matchedBy: "sarah.chen@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "Mastercard settlement",
  },
  {
    id: "M016",
    bankTransactionId: "B024",
    systemTransactionId: "S020",
    matchedAt: "2024-10-28T14:00:00Z",
    matchedBy: "sarah.chen@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "GBP/USD FX via Standard Chartered",
  },
  {
    id: "M017",
    bankTransactionId: "B025",
    systemTransactionId: "S021",
    matchedAt: "2024-10-27T10:10:00Z",
    matchedBy: "sarah.chen@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "Mastercard interchange revenue",
  },
];

export const exceptions: Exception[] = [
  {
    id: "E001",
    type: "amount_mismatch",
    severity: "medium",
    bankTransaction: bankTransactions[0],
    systemTransaction: systemTransactions[0],
    suggestedAction: "Match and post SGD 150 FX spread adjustment",
    description: "Bank amount (SGD 150,000) differs from system (SGD 149,850) by SGD 150 - FX spread variance",
  },
  {
    id: "E002",
    type: "unmatched",
    severity: "low",
    bankTransaction: bankTransactions[3],
    suggestedAction: "Create cross-border fee expense entry",
    description: "Cross-border payment fee with no matching system entry",
  },
  {
    id: "E003",
    type: "timing",
    severity: "low",
    description: "18 partner settlements recorded today, expected to clear within 2 business days",
  },
  {
    id: "E004",
    type: "duplicate",
    severity: "medium",
    description: "12 potential duplicate FX settlements detected across multiple currency pools",
  },
  {
    id: "E005",
    type: "amount_mismatch",
    severity: "medium",
    bankTransaction: bankTransactions[10],
    systemTransaction: systemTransactions[8],
    suggestedAction: "Match and post SGD 75 FX spread adjustment",
    description: "Bank amount (SGD 95,000) differs from system (SGD 94,925) by SGD 75 - GBP/SGD FX spread",
  },
  {
    id: "E006",
    type: "unmatched",
    severity: "low",
    bankTransaction: bankTransactions[9],
    suggestedAction: "Create SWIFT fee expense entry",
    description: "SWIFT wire transfer fee USD 45 with no matching system entry",
  },
  {
    id: "E007",
    type: "unmatched",
    severity: "low",
    bankTransaction: bankTransactions[15],
    suggestedAction: "Record monthly maintenance fee",
    description: "Monthly account maintenance fee SGD 250 requires system booking",
  },
  {
    id: "E008",
    type: "timing",
    severity: "medium",
    bankTransaction: bankTransactions[16],
    systemTransaction: systemTransactions[13],
    suggestedAction: "Monitor for T+2 settlement completion",
    description: "Treasury JPY pool settlement JPY 8.5M - T+2 settlement expected by EOD Oct 31",
  },
  {
    id: "E009",
    type: "unmatched",
    severity: "medium",
    bankTransaction: bankTransactions[20],
    suggestedAction: "Investigate incoming wire and create system entry",
    description: "Unmatched incoming cross-border wire SGD 250,000 - source verification required",
  },
  {
    id: "E010",
    type: "amount_mismatch",
    severity: "low",
    bankTransaction: bankTransactions[22],
    systemTransaction: systemTransactions[18],
    suggestedAction: "Match and post USD 50 API usage variance",
    description: "API usage fee variance - Bank USD 28,000 vs System USD 27,950 (USD 50 difference)",
  },
  {
    id: "E011",
    type: "unmatched",
    severity: "medium",
    systemTransaction: systemTransactions[21],
    suggestedAction: "Follow up on Partner E settlement status",
    description: "Expected partner settlement SGD 55,000 from Partner E not yet received",
  },
  {
    id: "E012",
    type: "unmatched",
    severity: "low",
    systemTransaction: systemTransactions[22],
    suggestedAction: "Match to bank charges or write off",
    description: "Expected cross-currency swap fee USD 320 not reflected in bank statement",
  },
];
