export interface Transaction {
  id: string;
  date: string;
  description: string;
  reference: string;
  amount: number;
  currency: string;
  type: "bank" | "system";
  status: "matched" | "unmatched" | "pending" | "exception";
  matchConfidence?: number;
  category?: string;
  partner?: string;
  bankAccount?: string;
  accountNumber?: string;
}

export interface DashboardStats {
  totalTransactions: number;
  autoMatched: number;
  exceptions: number;
  matchRate: number;
  accounts: AccountStatus[];
}

export interface AccountStatus {
  id: string;
  bank: string;
  segment: string;
  currency: string;
  accountNumber: string;
  balance: number;
  status: "reconciled" | "pending" | "critical";
  lastReconciled: string;
}

export const dashboardStats: DashboardStats = {
  totalTransactions: 2847,
  autoMatched: 2720,
  exceptions: 127,
  matchRate: 95.5,
  accounts: [
    {
      id: "ACC001",
      bank: "OCBC",
      segment: "Customer Segment",
      currency: "SGD",
      accountNumber: "8234-567890",
      balance: 12500000,
      status: "reconciled",
      lastReconciled: "2024-10-30 09:35 AM",
    },
    {
      id: "ACC002",
      bank: "OCBC",
      segment: "Customer Segment",
      currency: "USD",
      accountNumber: "8234-567891",
      balance: 8750000,
      status: "reconciled",
      lastReconciled: "2024-10-30 09:32 AM",
    },
    {
      id: "ACC003",
      bank: "OCBC",
      segment: "Operations",
      currency: "USD",
      accountNumber: "8234-567892",
      balance: 3200000,
      status: "pending",
      lastReconciled: "2024-10-29 04:15 PM",
    },
    {
      id: "ACC004",
      bank: "OCBC",
      segment: "Operations",
      currency: "SGD",
      accountNumber: "8234-567893",
      balance: 5400000,
      status: "reconciled",
      lastReconciled: "2024-10-30 08:45 AM",
    },
    {
      id: "ACC005",
      bank: "DBS",
      segment: "Customer Segment",
      currency: "SGD",
      accountNumber: "0012-345678",
      balance: 18900000,
      status: "reconciled",
      lastReconciled: "2024-10-30 10:15 AM",
    },
    {
      id: "ACC006",
      bank: "DBS",
      segment: "Customer Segment",
      currency: "USD",
      accountNumber: "0012-345679",
      balance: 11300000,
      status: "reconciled",
      lastReconciled: "2024-10-30 10:10 AM",
    },
    {
      id: "ACC007",
      bank: "DBS",
      segment: "Operations",
      currency: "USD",
      accountNumber: "0012-345680",
      balance: 2850000,
      status: "critical",
      lastReconciled: "2024-10-28 03:20 PM",
    },
    {
      id: "ACC008",
      bank: "DBS",
      segment: "Operations",
      currency: "SGD",
      accountNumber: "0012-345681",
      balance: 4700000,
      status: "pending",
      lastReconciled: "2024-10-29 02:30 PM",
    },
  ],
};

export const bankTransactions: Transaction[] = [
  // 3rd Party Cross-Border Payments (FX-involved) - 8 transactions
  {
    id: "B001",
    date: "2024-10-30",
    description: "CROSS-BORDER PAYMENT USD/SGD - MERCHANT A",
    reference: "CBP-USD-SGD-1045",
    amount: 150000,
    currency: "SGD",
    type: "bank",
    status: "exception",
    category: "Cross-Border Payment",
    partner: "Merchant A Pte Ltd",
    bankAccount: "OCBC Customer Segment SGD",
    accountNumber: "8234-567890",
  },
  {
    id: "B002",
    date: "2024-10-30",
    description: "CROSS-BORDER PAYMENT EUR/USD - VENDOR B",
    reference: "CBP-EUR-USD-8842",
    amount: 45000,
    currency: "USD",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "Cross-Border Payment",
    partner: "Vendor B GmbH",
    bankAccount: "DBS Customer Segment USD",
    accountNumber: "0012-345679",
  },
  {
    id: "B003",
    date: "2024-10-29",
    description: "CROSS-BORDER PAYMENT GBP/SGD - SUPPLIER C",
    reference: "CBP-GBP-SGD-1092",
    amount: 95000,
    currency: "SGD",
    type: "bank",
    status: "exception",
    category: "Cross-Border Payment",
    partner: "Supplier C Ltd",
    bankAccount: "DBS Customer Segment SGD",
    accountNumber: "0012-345678",
  },
  {
    id: "B004",
    date: "2024-10-29",
    description: "CROSS-BORDER PAYMENT JPY/USD - PARTNER D",
    reference: "CBP-JPY-USD-3087",
    amount: 85000,
    currency: "USD",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "Cross-Border Payment",
    partner: "Partner D KK",
    bankAccount: "OCBC Customer Segment USD",
    accountNumber: "8234-567891",
  },
  {
    id: "B005",
    date: "2024-10-28",
    description: "CROSS-BORDER PAYMENT USD/EUR - MERCHANT E",
    reference: "CBP-USD-EUR-7712",
    amount: 62000,
    currency: "EUR",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "Cross-Border Payment",
    partner: "Merchant E SA",
    bankAccount: "DBS Customer Segment USD",
    accountNumber: "0012-345679",
  },
  {
    id: "B006",
    date: "2024-10-27",
    description: "CROSS-BORDER PAYMENT GBP/USD - VENDOR F",
    reference: "CBP-GBP-USD-2845",
    amount: 125000,
    currency: "USD",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "Cross-Border Payment",
    partner: "Vendor F plc",
    bankAccount: "OCBC Customer Segment USD",
    accountNumber: "8234-567891",
  },
  {
    id: "B007",
    date: "2024-10-26",
    description: "CROSS-BORDER PAYMENT SGD/USD - SUPPLIER G",
    reference: "CBP-SGD-USD-5521",
    amount: 38000,
    currency: "USD",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "Cross-Border Payment",
    partner: "Supplier G Inc",
    bankAccount: "DBS Customer Segment USD",
    accountNumber: "0012-345679",
  },
  {
    id: "B008",
    date: "2024-10-25",
    description: "CROSS-BORDER PAYMENT EUR/SGD - PARTNER H",
    reference: "CBP-EUR-SGD-9103",
    amount: 178000,
    currency: "SGD",
    type: "bank",
    status: "unmatched",
    category: "Cross-Border Payment",
    partner: "Partner H BV",
    bankAccount: "OCBC Customer Segment SGD",
    accountNumber: "8234-567890",
  },

  // 3rd Party Collections (Payins) - 8 transactions
  {
    id: "B009",
    date: "2024-10-30",
    description: "CUSTOMER PAYMENT COLLECTION - INVOICE INV-2024-1234",
    reference: "PAYIN-1234-3001",
    amount: 55000,
    currency: "SGD",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "3rd Party Collection",
    partner: "Customer ABC Pte Ltd",
    bankAccount: "DBS Customer Segment SGD",
    accountNumber: "0012-345678",
  },
  {
    id: "B010",
    date: "2024-10-30",
    description: "MERCHANT SETTLEMENT - PAYMENT GATEWAY",
    reference: "PAYIN-GATEWAY-8821",
    amount: 92000,
    currency: "USD",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "3rd Party Collection",
    partner: "Payment Gateway Solutions",
    bankAccount: "OCBC Customer Segment USD",
    accountNumber: "8234-567891",
  },
  {
    id: "B011",
    date: "2024-10-29",
    description: "CUSTOMER PAYMENT - INVOICE INV-2024-1567",
    reference: "PAYIN-1567-2910",
    amount: 28000,
    currency: "USD",
    type: "bank",
    status: "exception",
    category: "3rd Party Collection",
    partner: "Customer XYZ Inc",
    bankAccount: "DBS Customer Segment USD",
    accountNumber: "0012-345679",
  },
  {
    id: "B012",
    date: "2024-10-28",
    description: "SUBSCRIPTION PAYMENT COLLECTION",
    reference: "PAYIN-SUB-2810",
    amount: 15000,
    currency: "SGD",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "3rd Party Collection",
    partner: "Subscriber DEF Ltd",
    bankAccount: "OCBC Customer Segment SGD",
    accountNumber: "8234-567890",
  },
  {
    id: "B013",
    date: "2024-10-27",
    description: "PAYMENT PROCESSOR SETTLEMENT",
    reference: "PAYIN-PROC-2710",
    amount: 145000,
    currency: "USD",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "3rd Party Collection",
    partner: "Stripe Asia Pte Ltd",
    bankAccount: "OCBC Customer Segment USD",
    accountNumber: "8234-567891",
  },
  {
    id: "B014",
    date: "2024-10-27",
    description: "CUSTOMER PAYMENT - BULK INVOICE BATCH",
    reference: "PAYIN-BULK-2709",
    amount: 68000,
    currency: "SGD",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "3rd Party Collection",
    partner: "Customer GHI Pte Ltd",
    bankAccount: "DBS Customer Segment SGD",
    accountNumber: "0012-345678",
  },
  {
    id: "B015",
    date: "2024-10-26",
    description: "MERCHANT PAYMENT COLLECTION",
    reference: "PAYIN-MERCH-2610",
    amount: 33500,
    currency: "USD",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "3rd Party Collection",
    partner: "Merchant JKL Inc",
    bankAccount: "DBS Customer Segment USD",
    accountNumber: "0012-345679",
  },
  {
    id: "B016",
    date: "2024-10-25",
    description: "CUSTOMER PAYMENT - INVOICE INV-2024-1890",
    reference: "PAYIN-1890-2510",
    amount: 42000,
    currency: "EUR",
    type: "bank",
    status: "unmatched",
    category: "3rd Party Collection",
    partner: "Customer MNO GmbH",
    bankAccount: "OCBC Customer Segment USD",
    accountNumber: "8234-567891",
  },

  // 1st Party Deposits (Wallet Funding) - 3 transactions
  {
    id: "B017",
    date: "2024-10-30",
    description: "WALLET FUNDING - SGD BALANCE TOP-UP",
    reference: "DEPOSIT-SGD-3001",
    amount: 500000,
    currency: "SGD",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "1st Party Deposit",
    partner: "Own Account - DBS",
    bankAccount: "DBS Operations SGD",
    accountNumber: "0012-345681",
  },
  {
    id: "B018",
    date: "2024-10-28",
    description: "WALLET FUNDING - USD BALANCE TOP-UP",
    reference: "DEPOSIT-USD-2810",
    amount: 250000,
    currency: "USD",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "1st Party Deposit",
    partner: "Own Account - OCBC",
    bankAccount: "OCBC Operations USD",
    accountNumber: "8234-567892",
  },
  {
    id: "B019",
    date: "2024-10-26",
    description: "WALLET FUNDING - EUR BALANCE TOP-UP",
    reference: "DEPOSIT-EUR-2610",
    amount: 180000,
    currency: "EUR",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "1st Party Deposit",
    partner: "Own Account - Standard Chartered",
    bankAccount: "OCBC Operations USD",
    accountNumber: "8234-567892",
  },

  // Bank Charges - 3 transactions
  {
    id: "B020",
    date: "2024-10-29",
    description: "MONTHLY ACCOUNT MAINTENANCE FEE",
    reference: "CHARGE-MAINT-OCT24",
    amount: -250,
    currency: "SGD",
    type: "bank",
    status: "unmatched",
    category: "Bank Charge",
    bankAccount: "OCBC Operations SGD",
    accountNumber: "8234-567893",
  },
  {
    id: "B021",
    date: "2024-10-27",
    description: "SWIFT WIRE TRANSFER CHARGE",
    reference: "CHARGE-SWIFT-2710",
    amount: -45,
    currency: "USD",
    type: "bank",
    status: "unmatched",
    category: "Bank Charge",
    bankAccount: "DBS Operations USD",
    accountNumber: "0012-345680",
  },
  {
    id: "B022",
    date: "2024-10-25",
    description: "STATEMENT GENERATION FEE",
    reference: "CHARGE-STMT-OCT24",
    amount: -15,
    currency: "SGD",
    type: "bank",
    status: "unmatched",
    category: "Bank Charge",
    bankAccount: "DBS Operations SGD",
    accountNumber: "0012-345681",
  },

  // Bank Fees - 2 transactions
  {
    id: "B023",
    date: "2024-10-28",
    description: "CROSS-BORDER PAYMENT PROCESSING FEE",
    reference: "FEE-CBP-2810",
    amount: -385,
    currency: "USD",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "Bank Fee",
    bankAccount: "OCBC Operations USD",
    accountNumber: "8234-567892",
  },
  {
    id: "B024",
    date: "2024-10-26",
    description: "WIRE TRANSFER FEE - INTERNATIONAL",
    reference: "FEE-WIRE-2610",
    amount: -125,
    currency: "SGD",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "Bank Fee",
    bankAccount: "OCBC Operations SGD",
    accountNumber: "8234-567893",
  },

  // Refunds - 1 transaction
  {
    id: "B025",
    date: "2024-10-27",
    description: "CUSTOMER REFUND - INVOICE INV-2024-0987",
    reference: "REFUND-0987-2710",
    amount: -18500,
    currency: "USD",
    type: "bank",
    status: "matched",
    matchConfidence: 100,
    category: "Refund",
    partner: "Customer PQR Ltd",
    bankAccount: "DBS Customer Segment USD",
    accountNumber: "0012-345679",
  },
];

export const systemTransactions: Transaction[] = [
  // 3rd Party Cross-Border Payments (FX-involved) - 8 transactions
  {
    id: "S001",
    date: "2024-10-30",
    description: "Cross-Border Payment Expected - Merchant A",
    reference: "CBP-USD-SGD-1045",
    amount: 149850,
    currency: "SGD",
    type: "system",
    status: "exception",
    category: "Cross-Border Payment",
    partner: "Merchant A Pte Ltd",
  },
  {
    id: "S002",
    date: "2024-10-30",
    description: "Cross-Border Payment Booking - Vendor B",
    reference: "CBP-EUR-USD-8842",
    amount: 45000,
    currency: "USD",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "Cross-Border Payment",
    partner: "Vendor B GmbH",
  },
  {
    id: "S003",
    date: "2024-10-29",
    description: "Cross-Border Payment Expected - Supplier C",
    reference: "CBP-GBP-SGD-1092",
    amount: 94925,
    currency: "SGD",
    type: "system",
    status: "exception",
    category: "Cross-Border Payment",
    partner: "Supplier C Ltd",
  },
  {
    id: "S004",
    date: "2024-10-29",
    description: "Cross-Border Payment Booking - Partner D",
    reference: "CBP-JPY-USD-3087",
    amount: 85000,
    currency: "USD",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "Cross-Border Payment",
    partner: "Partner D KK",
  },
  {
    id: "S005",
    date: "2024-10-28",
    description: "Cross-Border Payment Booking - Merchant E",
    reference: "CBP-USD-EUR-7712",
    amount: 62000,
    currency: "EUR",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "Cross-Border Payment",
    partner: "Merchant E SA",
  },
  {
    id: "S006",
    date: "2024-10-27",
    description: "Cross-Border Payment Booking - Vendor F",
    reference: "CBP-GBP-USD-2845",
    amount: 125000,
    currency: "USD",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "Cross-Border Payment",
    partner: "Vendor F plc",
  },
  {
    id: "S007",
    date: "2024-10-26",
    description: "Cross-Border Payment Booking - Supplier G",
    reference: "CBP-SGD-USD-5521",
    amount: 38000,
    currency: "USD",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "Cross-Border Payment",
    partner: "Supplier G Inc",
  },
  {
    id: "S008",
    date: "2024-10-25",
    description: "Cross-Border Payment Expected - Partner H",
    reference: "CBP-EUR-SGD-9103",
    amount: 178000,
    currency: "SGD",
    type: "system",
    status: "pending",
    category: "Cross-Border Payment",
    partner: "Partner H BV",
  },

  // 3rd Party Collections (Payins) - 8 transactions
  {
    id: "S009",
    date: "2024-10-30",
    description: "Customer Payment Expected - INV-2024-1234",
    reference: "PAYIN-1234-3001",
    amount: 55000,
    currency: "SGD",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "3rd Party Collection",
    partner: "Customer ABC Pte Ltd",
  },
  {
    id: "S010",
    date: "2024-10-30",
    description: "Merchant Settlement Booking",
    reference: "PAYIN-GATEWAY-8821",
    amount: 92000,
    currency: "USD",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "3rd Party Collection",
    partner: "Payment Gateway Solutions",
  },
  {
    id: "S011",
    date: "2024-10-29",
    description: "Customer Payment Expected - INV-2024-1567",
    reference: "PAYIN-1567-2910",
    amount: 27950,
    currency: "USD",
    type: "system",
    status: "exception",
    category: "3rd Party Collection",
    partner: "Customer XYZ Inc",
  },
  {
    id: "S012",
    date: "2024-10-28",
    description: "Subscription Payment Booking",
    reference: "PAYIN-SUB-2810",
    amount: 15000,
    currency: "SGD",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "3rd Party Collection",
    partner: "Subscriber DEF Ltd",
  },
  {
    id: "S013",
    date: "2024-10-27",
    description: "Payment Processor Settlement Booking",
    reference: "PAYIN-PROC-2710",
    amount: 145000,
    currency: "USD",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "3rd Party Collection",
    partner: "Stripe Asia Pte Ltd",
  },
  {
    id: "S014",
    date: "2024-10-27",
    description: "Customer Payment Bulk Batch",
    reference: "PAYIN-BULK-2709",
    amount: 68000,
    currency: "SGD",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "3rd Party Collection",
    partner: "Customer GHI Pte Ltd",
  },
  {
    id: "S015",
    date: "2024-10-26",
    description: "Merchant Payment Booking",
    reference: "PAYIN-MERCH-2610",
    amount: 33500,
    currency: "USD",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "3rd Party Collection",
    partner: "Merchant JKL Inc",
  },
  {
    id: "S016",
    date: "2024-10-29",
    description: "Customer Payment Expected - INV-2024-2045",
    reference: "PAYIN-2045-2910",
    amount: 75000,
    currency: "SGD",
    type: "system",
    status: "pending",
    category: "3rd Party Collection",
    partner: "Customer RST Pte Ltd",
  },

  // 1st Party Deposits (Wallet Funding) - 3 transactions
  {
    id: "S017",
    date: "2024-10-30",
    description: "Wallet Top-Up SGD Balance",
    reference: "DEPOSIT-SGD-3001",
    amount: 500000,
    currency: "SGD",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "1st Party Deposit",
    partner: "Own Account - DBS",
  },
  {
    id: "S018",
    date: "2024-10-28",
    description: "Wallet Top-Up USD Balance",
    reference: "DEPOSIT-USD-2810",
    amount: 250000,
    currency: "USD",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "1st Party Deposit",
    partner: "Own Account - OCBC",
  },
  {
    id: "S019",
    date: "2024-10-26",
    description: "Wallet Top-Up EUR Balance",
    reference: "DEPOSIT-EUR-2610",
    amount: 180000,
    currency: "EUR",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "1st Party Deposit",
    partner: "Own Account - Standard Chartered",
  },

  // Bank Fees - 2 transactions
  {
    id: "S020",
    date: "2024-10-28",
    description: "Cross-Border Payment Processing Fee Expected",
    reference: "FEE-CBP-2810",
    amount: -385,
    currency: "USD",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "Bank Fee",
  },
  {
    id: "S021",
    date: "2024-10-26",
    description: "Wire Transfer Fee Expected",
    reference: "FEE-WIRE-2610",
    amount: -125,
    currency: "SGD",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "Bank Fee",
  },

  // Refunds - 1 transaction
  {
    id: "S022",
    date: "2024-10-27",
    description: "Customer Refund Booking - INV-2024-0987",
    reference: "REFUND-0987-2710",
    amount: -18500,
    currency: "USD",
    type: "system",
    status: "matched",
    matchConfidence: 100,
    category: "Refund",
    partner: "Customer PQR Ltd",
  },
];

export interface MatchAdjustment {
  type: "fx_spread" | "timing" | "fee" | "other";
  amount: number;
  currency: string;
  description: string;
}

export interface MatchRecord {
  id: string;
  bankTransactionId: string;
  systemTransactionId: string;
  matchedAt: string;
  matchedBy: string;
  matchType: "auto" | "manual";
  matchConfidence: number;
  adjustments?: MatchAdjustment[];
  notes?: string;
}

export interface Exception {
  id: string;
  type: "timing" | "duplicate" | "amount_mismatch" | "unmatched";
  severity: "low" | "medium" | "high";
  bankTransaction?: Transaction;
  systemTransaction?: Transaction;
  suggestedAction?: string;
  description: string;
}

export const matchRecords: MatchRecord[] = [
  {
    id: "M001",
    bankTransactionId: "B002",
    systemTransactionId: "S002",
    matchedAt: "2024-10-30T09:35:00Z",
    matchedBy: "sarah.chen@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "Cross-border payment EUR/USD - exact match",
  },
  {
    id: "M002",
    bankTransactionId: "B004",
    systemTransactionId: "S004",
    matchedAt: "2024-10-29T10:20:00Z",
    matchedBy: "sarah.chen@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "Cross-border payment JPY/USD - exact match",
  },
  {
    id: "M003",
    bankTransactionId: "B005",
    systemTransactionId: "S005",
    matchedAt: "2024-10-28T14:15:00Z",
    matchedBy: "sarah.chen@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "Cross-border payment USD/EUR - exact match",
  },
  {
    id: "M004",
    bankTransactionId: "B006",
    systemTransactionId: "S006",
    matchedAt: "2024-10-27T11:30:00Z",
    matchedBy: "michael.wong@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "Cross-border payment GBP/USD - exact match",
  },
  {
    id: "M005",
    bankTransactionId: "B007",
    systemTransactionId: "S007",
    matchedAt: "2024-10-26T15:45:00Z",
    matchedBy: "sarah.chen@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "Cross-border payment SGD/USD - exact match",
  },
  {
    id: "M006",
    bankTransactionId: "B009",
    systemTransactionId: "S009",
    matchedAt: "2024-10-30T09:40:00Z",
    matchedBy: "sarah.chen@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "Customer payment collection - exact match on invoice reference",
  },
  {
    id: "M007",
    bankTransactionId: "B010",
    systemTransactionId: "S010",
    matchedAt: "2024-10-30T09:38:00Z",
    matchedBy: "sarah.chen@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "Merchant settlement via payment gateway",
  },
  {
    id: "M008",
    bankTransactionId: "B012",
    systemTransactionId: "S012",
    matchedAt: "2024-10-28T11:05:00Z",
    matchedBy: "sarah.chen@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "Subscription payment collection",
  },
  {
    id: "M009",
    bankTransactionId: "B013",
    systemTransactionId: "S013",
    matchedAt: "2024-10-27T16:30:00Z",
    matchedBy: "michael.wong@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "Payment processor settlement - Stripe",
  },
  {
    id: "M010",
    bankTransactionId: "B014",
    systemTransactionId: "S014",
    matchedAt: "2024-10-27T14:20:00Z",
    matchedBy: "sarah.chen@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "Customer payment bulk batch",
  },
  {
    id: "M011",
    bankTransactionId: "B015",
    systemTransactionId: "S015",
    matchedAt: "2024-10-26T10:50:00Z",
    matchedBy: "sarah.chen@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "Merchant payment collection",
  },
  {
    id: "M012",
    bankTransactionId: "B017",
    systemTransactionId: "S017",
    matchedAt: "2024-10-30T09:15:00Z",
    matchedBy: "sarah.chen@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "Wallet funding - SGD balance top-up",
  },
  {
    id: "M013",
    bankTransactionId: "B018",
    systemTransactionId: "S018",
    matchedAt: "2024-10-28T13:25:00Z",
    matchedBy: "michael.wong@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "Wallet funding - USD balance top-up",
  },
  {
    id: "M014",
    bankTransactionId: "B019",
    systemTransactionId: "S019",
    matchedAt: "2024-10-26T14:40:00Z",
    matchedBy: "sarah.chen@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "Wallet funding - EUR balance top-up",
  },
  {
    id: "M015",
    bankTransactionId: "B023",
    systemTransactionId: "S020",
    matchedAt: "2024-10-28T11:50:00Z",
    matchedBy: "jessica.tan@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "Cross-border payment processing fee",
  },
  {
    id: "M016",
    bankTransactionId: "B024",
    systemTransactionId: "S021",
    matchedAt: "2024-10-26T16:10:00Z",
    matchedBy: "sarah.chen@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "Wire transfer fee",
  },
  {
    id: "M017",
    bankTransactionId: "B025",
    systemTransactionId: "S022",
    matchedAt: "2024-10-27T10:30:00Z",
    matchedBy: "jessica.tan@matchmaker.io",
    matchType: "auto",
    matchConfidence: 100,
    notes: "Customer refund processed",
  },
];

export const exceptions: Exception[] = [
  {
    id: "E001",
    type: "amount_mismatch",
    severity: "medium",
    bankTransaction: bankTransactions[0],
    systemTransaction: systemTransactions[0],
    suggestedAction: "Match and post SGD 150 FX spread adjustment",
    description: "Cross-border payment amount mismatch: Bank SGD 150,000 vs System SGD 149,850 - FX spread variance of SGD 150",
  },
  {
    id: "E002",
    type: "amount_mismatch",
    severity: "medium",
    bankTransaction: bankTransactions[2],
    systemTransaction: systemTransactions[2],
    suggestedAction: "Match and post SGD 75 FX spread adjustment",
    description: "Cross-border payment GBP/SGD: Bank SGD 95,000 vs System SGD 94,925 - FX spread variance of SGD 75",
  },
  {
    id: "E003",
    type: "amount_mismatch",
    severity: "low",
    bankTransaction: bankTransactions[10],
    systemTransaction: systemTransactions[10],
    suggestedAction: "Match and post USD 50 collection variance adjustment",
    description: "Customer payment collection variance: Bank USD 28,000 vs System USD 27,950 - variance of USD 50",
  },
  {
    id: "E004",
    type: "unmatched",
    severity: "medium",
    bankTransaction: bankTransactions[7],
    suggestedAction: "Follow up on EUR/SGD cross-border payment status and match to system",
    description: "Unmatched cross-border payment: EUR/SGD payment of SGD 178,000 from Partner H not yet matched to system record",
  },
  {
    id: "E005",
    type: "unmatched",
    severity: "medium",
    bankTransaction: bankTransactions[15],
    suggestedAction: "Follow up with Customer MNO on payment status",
    description: "Unmatched customer payment collection: EUR 42,000 payment not yet matched to system booking",
  },
  {
    id: "E006",
    type: "unmatched",
    severity: "low",
    bankTransaction: bankTransactions[19],
    suggestedAction: "Create bank charge expense entry in system",
    description: "Monthly account maintenance fee SGD 250 - no matching system entry",
  },
  {
    id: "E007",
    type: "unmatched",
    severity: "low",
    bankTransaction: bankTransactions[20],
    suggestedAction: "Create bank charge expense entry for SWIFT fee",
    description: "SWIFT wire transfer charge USD 45 - no matching system entry",
  },
  {
    id: "E008",
    type: "unmatched",
    severity: "low",
    bankTransaction: bankTransactions[21],
    suggestedAction: "Record statement generation fee in system",
    description: "Statement generation fee SGD 15 - no matching system entry",
  },
  {
    id: "E009",
    type: "unmatched",
    severity: "medium",
    systemTransaction: systemTransactions[7],
    suggestedAction: "Monitor for T+2 settlement - expected by Oct 31",
    description: "Expected cross-border payment EUR/SGD from Partner H - system booking SGD 178,000 awaiting bank receipt",
  },
  {
    id: "E010",
    type: "unmatched",
    severity: "medium",
    systemTransaction: systemTransactions[15],
    suggestedAction: "Follow up with Customer RST on payment INV-2024-2045",
    description: "Expected customer payment SGD 75,000 - system booking created but payment not yet received",
  },
  {
    id: "E011",
    type: "timing",
    severity: "low",
    description: "2 cross-border payments pending settlement - expected to clear within T+2 business days",
  },
  {
    id: "E012",
    type: "duplicate",
    severity: "low",
    description: "No duplicate transactions detected - all references are unique",
  },
];
